### ISSUE TITLE
Example Needed & nuGet Package?

### ISSUE THREAD

**Issue by waliarubal** [aljazsim/torrent-client-for-net#2]
Can you provide an end-to-end (complete) example for downloading files via a .torrent file using your library?

Do you have a nuGet package also?

**Comment by PoLaKoSz** [comment]
- Clone the repository
- Open the .sln file (`Src\TorrentClient.sln`)
- Open the Program.cs file inside the TorrentClientApp
- Change the torrent file path inside the Main method
```` csharp
TorrentInfo.TryLoad(@".\..\..\Test\TorrentClientTest.Data\TorrentFile.torrent", out torrent);
````
to this
```` csharp
TorrentInfo.TryLoad("Torrent.torrent", out torrent);
````
- [Download](https://yts.am/) a `.torrrent` file
- Rebuild the `TorrentClientApp` (Visual Studio 2017 will take care of everything)
- Place the downloaded .torrent file to the `torrent-client-for-net\Binaries\TorrentClientApp\` folder
- Rename it to `Torrent.torrent`
- Run the TorrentClientApp

**Comment by aljazsim** [comment]
Thank you for the help PoLaKoSz  :) Much appreciated. And I'm glad somebody is actually using the library! As for the nuget package, the project is not available via nuget. If you want to include the library in your project I suggest you include a release version of the dll which you can compile yourself or include the entire project in your solution.

**Comment by waliarubal** [comment]
I would recommend creating a nuGet package of this project. This will help others in referencing library easily. .NET Framework 4 would be cool since I target it to support windows XP also. :)
