### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [aljazsim/torrent-client-for-net#3]
Hey I have problem with connection, first time I use app take 7min20sec to connect... too long i think. But when I run app again cant connect now i try few times but doesnt work.

How fix it?

**Comment by aljazsim** [comment]
Could it be that on the first try there were no available seeders?

**Comment by aljazsim** [comment]
Could you try with a different torrent info file to see if the issue persists?

**Comment by 15w34r0n3D4y** [comment]
After a few tries connected but after 27min, i try it local there is 1 seeder.

**Comment by aljazsim** [comment]
Are you maybe using a firewall or an antivirus that is blocking the connection? The reason I'm asking is that I've never experienced such a delay. Especially locally.

**Comment by 15w34r0n3D4y** [comment]
I try public torrent and works fine and fast connect with 1xxx seeder, sorry you can delete this issue.

**Comment by aljazsim** [comment]
I'm glad to hear that. If you ever figure out what the issue was, please let me know.
