### ISSUE TITLE
Not working with private tracker

### ISSUE THREAD

**Issue by billy193** [aljazsim/torrent-client-for-net#5]
I’m trying to download a torrent that uses private tracker that supports BitTorrent but it’s not working wit this client. It can’t find any peers or anything I verified it works with BitTorrent

**Comment by aljazsim** [comment]
Hi Billy.

This was originally meant to be a BitTorrent 1.0 implementation. If you'd like include support for private trackers I encourage you to implement it and submit a PR and I'll be more than happy to include this functionality to the main branch.
