### ISSUE TITLE
Super Slow Download Speeds

### ISSUE THREAD

**Issue by calico-crusade** [aljazsim/torrent-client-for-net#6]
I'm attempting to use torrent-client-for-net, however, I think I might be missing something. 
I am getting max download speeds of 72kBs, while UTorrent is reporting 3mBs+ for the same torrent on the same computer. 

This isn't feasible by any stretch. Am I doing something wrong? I downloaded the project as is, and just changed the .torrent file.

**Comment by calico-crusade** [comment]
Apparently, I'm just an idiot. I did not save my changes to the Max Download Speed before running.

**Comment by aljazsim** [comment]
No worries :)
