### ISSUE TITLE
Can't download torrent

### ISSUE THREAD

**Issue by CakesTwix** [aljazsim/torrent-client-for-net#7]
> using System;
> using System.Threading;
> using System.Threading.Tasks;
> using TorrentClient;
> 
> namespace Test
> 
> {
>     class Program
>     {
>         
>         static void Main(string[] args)
>         {
>             TorrentInfo.TryLoad(@"C:\Users\CakesTwix\Downloads\11628.torrent", out TorrentInfo torrent);
>             Console.Read();
>         }
>     }
> }

![изображение](https://user-images.githubusercontent.com/57946485/91659808-e3922f80-eada-11ea-9404-5969253ce4dc.png)

> System.IO.FileNotFoundException: "Could not load file or assembly" netstandard, Version = 2.1.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51 "or one of their dependencies. The specified file could not be found."

**Comment by aljazsim** [comment]
Hi @CakesTwix.

I'm not experiencing any issues on my machine. You can try this if it helps: https://github.com/dotnet/standard/issues/542#issuecomment-339516364
